---
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

dist: trusty

sudo: false
addons:
  chrome: stable

cache:
  yarn: true

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - node_js: "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn lint:js
  - yarn test

before_deploy:
  - yarn global add auto-dist-tag
  - auto-dist-tag --write

deploy:
  skip_cleanup: true
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: OVMYTMjIiSuBxCB0vQZJfaQzyeaR0U5dgRZaoc5CRd4yys9i+rL3PlJaWeeO6Lm950j+v6fDKHZg6aMLAhLOosZfkLEZh0ycvBSKq//ZI5yAhqnp9LV7/FGCEBT0ij1Mp3cqCaIlQIZjPo6lS+hIsYf3tqg1/cw2VOtDO4RprJ4=
  on:
    tags: true
    repo: babel/ember-cli-babel
