language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "iojs"
before_install:
    - npm install -g bower
    - npm install -g ember-cli
install:
    - bower install
    - npm install
script: ember test
notifications:
    email: false
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "iojs"
