language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
install:
  - npm install
  - npm run bower:install
script:
  - npm run jshint .
  - npm test
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "iojs"
